// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYSdARZgm27tmgSjJMS3amiE7sGnM-_yg',
    appId: '1:612562021338:web:34bbe019523d8e5736aee3',
    messagingSenderId: '612562021338',
    projectId: 'projeto-ievent',
    authDomain: 'projeto-ievent.firebaseapp.com',
    storageBucket: 'projeto-ievent.appspot.com',
    measurementId: 'G-NLN4RM4FW7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9eAUmRl2YTwxEPjez3jkiLTL1lGFnv18',
    appId: '1:612562021338:android:c0f50eecc4cd2a8436aee3',
    messagingSenderId: '612562021338',
    projectId: 'projeto-ievent',
    storageBucket: 'projeto-ievent.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAI9jMZS5Poe6rGDXvEtu4QXZQl47n7pMQ',
    appId: '1:612562021338:ios:9e6821211527a94036aee3',
    messagingSenderId: '612562021338',
    projectId: 'projeto-ievent',
    storageBucket: 'projeto-ievent.appspot.com',
    iosClientId: '612562021338-nblm225uf0jlcstb4eq0ceabfn5d25ht.apps.googleusercontent.com',
    iosBundleId: 'com.example.ievent',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAI9jMZS5Poe6rGDXvEtu4QXZQl47n7pMQ',
    appId: '1:612562021338:ios:9e6821211527a94036aee3',
    messagingSenderId: '612562021338',
    projectId: 'projeto-ievent',
    storageBucket: 'projeto-ievent.appspot.com',
    iosClientId: '612562021338-nblm225uf0jlcstb4eq0ceabfn5d25ht.apps.googleusercontent.com',
    iosBundleId: 'com.example.ievent',
  );
}
