// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDExsiCva-bM3Mm17yByrd9hGqadhYW84w',
    appId: '1:805647857934:web:0f141efa3a168f2ff4ff5f',
    messagingSenderId: '805647857934',
    projectId: 'appievent',
    authDomain: 'appievent.firebaseapp.com',
    storageBucket: 'appievent.appspot.com',
    measurementId: 'G-KHJ2QW93WG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPpsbHqVJSiEm68YnXIPIVPviBN8wk2Jo',
    appId: '1:805647857934:android:480bf6a525fba182f4ff5f',
    messagingSenderId: '805647857934',
    projectId: 'appievent',
    storageBucket: 'appievent.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhfawyayhFFLppplMUp8JG2M24Z0F89q0',
    appId: '1:805647857934:ios:0b8a431634796662f4ff5f',
    messagingSenderId: '805647857934',
    projectId: 'appievent',
    storageBucket: 'appievent.appspot.com',
    iosBundleId: 'com.example.ievent',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDhfawyayhFFLppplMUp8JG2M24Z0F89q0',
    appId: '1:805647857934:ios:0b8a431634796662f4ff5f',
    messagingSenderId: '805647857934',
    projectId: 'appievent',
    storageBucket: 'appievent.appspot.com',
    iosBundleId: 'com.example.ievent',
  );
}
